#################################
#### apigateway-pilot1 ##########
#################################

info:
  component: Zuul Proxy  
---

spring:
  application:
    name: apigateway-pilot1
    
---
    
zuul:
  routes:
    pilot1:
      path: /pilot1/**
      serviceId: pilot-service2
      
---
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.250.228.140:8761/eureka/  