#################################
#### apigateway-pilot1 ##########
#################################

info:
  component: Zuul Proxy  
---

spring:
  application:
    name: apigateway-pilot2
    
---
    
#zuul:
#  ignoredServices: '*'
#  routes:
#    pilot1:
#      path: /pilot1/**
#      serviceId: pilot-service2
      
---
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.250.238.108:8761/eureka/  
