spring:
  profiles: dev
spring:
#Apache Kafka Binder for bus-kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.250.228.140:9092
          #defaultBrokerPort: 9092
          zkNodes: 10.250.228.140:2181
          #defaultZkPort: 2181
  thymeleaf.cache: false
logging.level.org.springframework.security: DEBUG

---

# custom properties
config-client2-welcome: hello, welcome to my dev11 world11111111
