server:
  port: 8092

---

spring:
  profiles:
    active: local
    
---

spring:
  profiles: local  
app:
  message: App refreshable message from development profile - Update 2222222222222

---
spring:
  profiles: dev
app:      
  message: App refreshable message from development profile==> DEV 22222