
spring:
  profiles:
    active: dev
    
---

spring:
  profiles: local  
app:
  message: App refreshable message from development profile - Update 78901234567888

---
spring:
  profiles: dev
app:      
  message: App refreshable message from development profile==> DEV 